<?php

use App\Http\Controllers\Admin\BatchController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ImageLibraryController;
use App\Http\Controllers\Admin\KnowledgeController;
use App\Http\Controllers\Admin\ReviewController;
use App\Http\Controllers\Admin\SettingsController;
use App\Http\Controllers\Admin\SkillController;
use App\Http\Controllers\Admin\TitleLibraryController;
use App\Http\Controllers\Admin\TopicSourceController;
use App\Http\Controllers\Admin\WordPressConnectionController;
use App\Http\Controllers\HealthController;
use Illuminate\Support\Facades\Route;

Route::get('/health', HealthController::class);
Route::get('/admin', [DashboardController::class, 'index'])->name('admin.dashboard');
Route::get('/admin/batches', [BatchController::class, 'index'])->name('admin.batches.index');
Route::post('/admin/batches/create-daily', [BatchController::class, 'createDaily'])->name('admin.batches.create-daily');
Route::post('/admin/content-items/{item}/generate', [BatchController::class, 'generateItem'])->name('admin.items.generate');
Route::post('/admin/content-items/{item}/review', [BatchController::class, 'reviewItem'])->name('admin.items.review');
Route::post('/admin/content-items/{item}/cancel', [BatchController::class, 'cancelItem'])->name('admin.items.cancel');
Route::get('/admin/sources', [TopicSourceController::class, 'index'])->name('admin.sources.index');
Route::post('/admin/sources', [TopicSourceController::class, 'store'])->name('admin.sources.store');
Route::post('/admin/sources/{source}/update', [TopicSourceController::class, 'update'])->name('admin.sources.update');
Route::post('/admin/sources/{source}/toggle', [TopicSourceController::class, 'toggle'])->name('admin.sources.toggle');
Route::post('/admin/sources/{source}/pause', [TopicSourceController::class, 'pause'])->name('admin.sources.pause');
Route::post('/admin/sources/{source}/delete', [TopicSourceController::class, 'destroy'])->name('admin.sources.destroy');
Route::post('/admin/sources/{source}/test', [TopicSourceController::class, 'test'])->name('admin.sources.test');
Route::post('/admin/sources/{source}/collect', [TopicSourceController::class, 'collect'])->name('admin.sources.collect');
Route::get('/admin/titles', [TitleLibraryController::class, 'index'])->name('admin.titles.index');
Route::post('/admin/titles', [TitleLibraryController::class, 'store'])->name('admin.titles.store');
Route::post('/admin/titles/import', [TitleLibraryController::class, 'import'])->name('admin.titles.import');
Route::post('/admin/titles/{title}/update', [TitleLibraryController::class, 'update'])->name('admin.titles.update');
Route::post('/admin/titles/{title}/toggle', [TitleLibraryController::class, 'toggle'])->name('admin.titles.toggle');
Route::post('/admin/titles/{title}/delete', [TitleLibraryController::class, 'destroy'])->name('admin.titles.delete');
Route::get('/admin/knowledge', [KnowledgeController::class, 'index'])->name('admin.knowledge.index');
Route::post('/admin/knowledge', [KnowledgeController::class, 'store'])->name('admin.knowledge.store');
Route::get('/admin/knowledge/{base}', [KnowledgeController::class, 'show'])->name('admin.knowledge.show');
Route::post('/admin/knowledge/{base}/update', [KnowledgeController::class, 'update'])->name('admin.knowledge.update');
Route::post('/admin/knowledge/{base}/delete', [KnowledgeController::class, 'destroy'])->name('admin.knowledge.destroy');
Route::post('/admin/knowledge/{base}/toggle', [KnowledgeController::class, 'toggle'])->name('admin.knowledge.toggle');
Route::post('/admin/knowledge/{base}/documents', [KnowledgeController::class, 'uploadDocuments'])->name('admin.knowledge.documents.upload');
Route::post('/admin/knowledge/{base}/documents/{document}/update', [KnowledgeController::class, 'updateDocument'])->name('admin.knowledge.documents.update');
Route::post('/admin/knowledge/{base}/documents/{document}/delete', [KnowledgeController::class, 'destroyDocument'])->name('admin.knowledge.documents.destroy');
Route::get('/admin/knowledge/{base}/documents/{document}/chunks', [KnowledgeController::class, 'chunks'])->name('admin.knowledge.documents.chunks');
Route::post('/admin/knowledge/{base}/test-retrieval', [KnowledgeController::class, 'testRetrieval'])->name('admin.knowledge.test-retrieval');
Route::get('/admin/images', [ImageLibraryController::class, 'index'])->name('admin.images.index');
Route::post('/admin/images', [ImageLibraryController::class, 'store'])->name('admin.images.store');
Route::get('/admin/images/{library}', [ImageLibraryController::class, 'show'])->name('admin.images.show');
Route::post('/admin/images/{library}/update', [ImageLibraryController::class, 'update'])->name('admin.images.update');
Route::post('/admin/images/{library}/delete', [ImageLibraryController::class, 'destroy'])->name('admin.images.delete');
Route::post('/admin/images/{library}/images', [ImageLibraryController::class, 'uploadImages'])->name('admin.images.upload');
Route::post('/admin/images/{library}/images/{image}/update', [ImageLibraryController::class, 'updateImage'])->name('admin.images.images.update');
Route::post('/admin/images/{library}/images/{image}/toggle', [ImageLibraryController::class, 'toggleImage'])->name('admin.images.images.toggle');
Route::post('/admin/images/{library}/images/{image}/delete', [ImageLibraryController::class, 'destroyImage'])->name('admin.images.images.destroy');
Route::post('/admin/images/{library}/match-test', [ImageLibraryController::class, 'matchTest'])->name('admin.images.match-test');
Route::get('/admin/image-files/{image}', [ImageLibraryController::class, 'serve'])->name('admin.images.file');
Route::get('/admin/wordpress', [WordPressConnectionController::class, 'index'])->name('admin.wordpress.index');
Route::get('/admin/settings', [SettingsController::class, 'index'])->name('admin.settings.index');
Route::post('/admin/settings', [SettingsController::class, 'update'])->name('admin.settings.update');
Route::post('/admin/settings/ai/{provider}/test', [SettingsController::class, 'testAiProvider'])->name('admin.settings.ai.test');
Route::get('/admin/settings/ai/{provider}/models', [SettingsController::class, 'listAiModels'])->name('admin.settings.ai.models');
Route::post('/admin/settings/wordpress/test', [SettingsController::class, 'testWordPress'])->name('admin.settings.wordpress.test');
Route::prefix('admin/skills')->name('admin.skills.')->group(function (): void {
    Route::get('/', [SkillController::class, 'index'])->name('index');
    Route::post('/', [SkillController::class, 'store'])->name('store');
    Route::post('/{skill}/enable', [SkillController::class, 'enable'])->name('enable');
    Route::post('/{skill}/disable', [SkillController::class, 'disable'])->name('disable');
    Route::post('/{skill}/versions', [SkillController::class, 'version'])->name('version');
});
Route::prefix('admin/reviews')->name('admin.reviews.')->group(function (): void {
    Route::get('/', [ReviewController::class, 'index'])->name('index');
    Route::get('/{contentItem}', [ReviewController::class, 'show'])->name('show');
    Route::post('/{contentItem}/approve', [ReviewController::class, 'approve'])->name('approve');
    Route::post('/{contentItem}/manual', [ReviewController::class, 'requestManual'])->name('manual');
    Route::post('/{contentItem}/write-draft', [ReviewController::class, 'writeDraft'])->name('write-draft');
    Route::post('/{contentItem}/update', [ReviewController::class, 'update'])->name('update');
    Route::post('/{contentItem}/rerun-review', [ReviewController::class, 'rerunReview'])->name('rerun-review');
});
