<?php

use App\Http\Controllers\Admin\BatchController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ImageLibraryController;
use App\Http\Controllers\Admin\KnowledgeController;
use App\Http\Controllers\Admin\ReviewController;
use App\Http\Controllers\Admin\SkillController;
use App\Http\Controllers\Admin\TitleLibraryController;
use App\Http\Controllers\Admin\TopicSourceController;
use App\Http\Controllers\Admin\WordPressConnectionController;
use App\Http\Controllers\Admin\SettingsController;
use App\Http\Controllers\HealthController;
use App\Http\Controllers\MediaPreviewController;
use App\Http\Controllers\Admin\TaskController;
use Illuminate\Support\Facades\Route;

Route::get('/health', HealthController::class);
Route::get('/media/images/{libraryImage}', [MediaPreviewController::class, 'show'])->name('media.images.show');
Route::get('/admin', [DashboardController::class, 'index'])->name('admin.dashboard');
Route::get('/admin/batches', [BatchController::class, 'index'])->name('admin.batches.index');
Route::get('/admin/tasks', [TaskController::class, 'index'])->name('admin.tasks.index');
Route::post('/admin/tasks', [TaskController::class, 'store'])->name('admin.tasks.store');
Route::post('/admin/tasks/{task}', [TaskController::class, 'update'])->name('admin.tasks.update');
Route::post('/admin/tasks/{task}/start', [TaskController::class, 'start'])->name('admin.tasks.start');
Route::post('/admin/tasks/{task}/pause', [TaskController::class, 'pause'])->name('admin.tasks.pause');
Route::post('/admin/tasks/{task}/run', [TaskController::class, 'run'])->name('admin.tasks.run');
Route::post('/admin/batches', [BatchController::class, 'store'])->name('admin.batches.store');
Route::get('/admin/batches/{batch}', [BatchController::class, 'show'])->name('admin.batches.show');
Route::post('/admin/batches/{batch}/run', [BatchController::class, 'run'])->name('admin.batches.run');
Route::post('/admin/batches/{batch}/retry', [BatchController::class, 'retry'])->name('admin.batches.retry');
Route::post('/admin/batches/{batch}/title-candidates/{titleCandidate}', [BatchController::class, 'selectTitle'])->name('admin.batches.title-candidates.select');
Route::get('/admin/sources', [TopicSourceController::class, 'index'])->name('admin.sources.index');
Route::post('/admin/sources', [TopicSourceController::class, 'store'])->name('admin.sources.store');
Route::post('/admin/sources/{topicSource}/toggle', [TopicSourceController::class, 'toggle'])->name('admin.sources.toggle');
Route::post('/admin/sources/{topicSource}/fetch', [TopicSourceController::class, 'fetch'])->name('admin.sources.fetch');
Route::post('/admin/sources/{topicSource}/preview', [TopicSourceController::class, 'preview'])->name('admin.sources.preview');
Route::get('/admin/titles', [TitleLibraryController::class, 'index'])->name('admin.titles.index');
Route::post('/admin/titles', [TitleLibraryController::class, 'store'])->name('admin.titles.store');
Route::post('/admin/titles/import', [TitleLibraryController::class, 'import'])->name('admin.titles.import');
Route::post('/admin/titles/{titleLibraryEntry}/toggle', [TitleLibraryController::class, 'toggle'])->name('admin.titles.toggle');
Route::get('/admin/knowledge', [KnowledgeController::class, 'index'])->name('admin.knowledge.index');
Route::post('/admin/knowledge', [KnowledgeController::class, 'store'])->name('admin.knowledge.store');
Route::post('/admin/knowledge/{knowledgeBase}/documents', [KnowledgeController::class, 'upload'])->name('admin.knowledge.documents.store');
Route::post('/admin/knowledge/{knowledgeBase}/toggle', [KnowledgeController::class, 'toggle'])->name('admin.knowledge.toggle');
Route::get('/admin/images', [ImageLibraryController::class, 'index'])->name('admin.images.index');
Route::post('/admin/images', [ImageLibraryController::class, 'store'])->name('admin.images.store');
Route::post('/admin/images/{imageLibrary}/upload', [ImageLibraryController::class, 'upload'])->name('admin.images.upload');
Route::post('/admin/images/{imageLibrary}/toggle', [ImageLibraryController::class, 'toggle'])->name('admin.images.toggle');
Route::post('/admin/images/items/{libraryImage}', [ImageLibraryController::class, 'updateImage'])->name('admin.images.items.update');
Route::get('/admin/wordpress', [WordPressConnectionController::class, 'index'])->name('admin.wordpress.index');
Route::post('/admin/wordpress', [WordPressConnectionController::class, 'store'])->name('admin.wordpress.store');
Route::post('/admin/wordpress/{connection}', [WordPressConnectionController::class, 'update'])->name('admin.wordpress.update');
Route::post('/admin/wordpress/{connection}/test', [WordPressConnectionController::class, 'test'])->name('admin.wordpress.test');
Route::post('/admin/wordpress/{connection}/diagnose', [WordPressConnectionController::class, 'diagnose'])->name('admin.wordpress.diagnose');
Route::get('/admin/settings', [SettingsController::class, 'index'])->name('admin.settings.index');
Route::post('/admin/settings', [SettingsController::class, 'update'])->name('admin.settings.update');
Route::get('/admin/settings/models', [SettingsController::class, 'models'])->name('admin.settings.models');
Route::post('/admin/settings/models', [SettingsController::class, 'models'])->name('admin.settings.models.fetch');
Route::post('/admin/settings/ai-role', [SettingsController::class, 'saveRole'])->name('admin.settings.ai-role.save');
Route::post('/admin/settings/connections', [SettingsController::class, 'storeConnection'])->name('admin.settings.connections.store');
Route::post('/admin/settings/routing', [SettingsController::class, 'updateRouting'])->name('admin.settings.routing.update');
Route::prefix('admin/skills')->name('admin.skills.')->group(function (): void {
    Route::get('/', [SkillController::class, 'index'])->name('index');
    Route::post('/', [SkillController::class, 'store'])->name('store');
    Route::post('/{skill}/enable', [SkillController::class, 'enable'])->name('enable');
    Route::post('/{skill}/disable', [SkillController::class, 'disable'])->name('disable');
    Route::post('/{skill}/versions', [SkillController::class, 'version'])->name('version');
});
Route::prefix('admin/reviews')->name('admin.reviews.')->group(function (): void {
    Route::get('/', [ReviewController::class, 'index'])->name('index');
    Route::get('/{contentItem}', [ReviewController::class, 'show'])->name('show');
    Route::post('/{contentItem}/approve', [ReviewController::class, 'approve'])->name('approve');
    Route::post('/{contentItem}/manual', [ReviewController::class, 'requestManual'])->name('manual');
    Route::post('/{contentItem}/write-draft', [ReviewController::class, 'writeDraft'])->name('write-draft');
    Route::post('/{contentItem}/retry', [ReviewController::class, 'retry'])->name('retry');
});
