@extends('admin.layout', ['title' => '批次详情'])
@section('content')
<div class="page-heading"><div><div class="eyebrow">批次详情</div><h1>{{ $batch->run_date->toDateString() }}</h1><p class="subtitle">{{ $batch->completed_count }}/{{ $batch->target_count }} 个选题已锁定。</p></div><div class="actions"><a class="button ghost" href="{{ route('admin.batches.index') }}">返回批次</a><form method="post" action="{{ route('admin.batches.run', $batch) }}">@csrf<button class="button" type="submit">运行生成</button></form><form method="post" action="{{ route('admin.batches.retry', $batch) }}">@csrf<button class="button warn" type="submit">重试失败项</button></form></div></div>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
<section class="stat-grid">@foreach(['locked'=>'待生成','generating'=>'生成中','awaiting_review'=>'待审核','needs_manual_review'=>'人工复核','approved'=>'已通过','retryable_failed'=>'待重试','wp_draft_written'=>'已写入草稿'] as $state=>$label)<div class="stat"><div class="stat-top"><span>{{ $label }}</span></div><strong>{{ $stats[$state] ?? 0 }}</strong></div>@endforeach</section>
@php($stateLabels = ['locked' => '待生成', 'generating' => '生成中', 'awaiting_review' => '等待审核', 'needs_manual_review' => '人工复核', 'approved' => '已通过', 'retryable_failed' => '待重试', 'wp_draft_written' => '已写入草稿', 'published' => '已发布'])
<section class="panel"><div class="panel-header"><div><h2>文章项</h2><p>点击标题进入审核详情。</p></div></div><div class="panel-body table-wrap"><table><thead><tr><th>标题</th><th>生成状态</th><th>最近运行</th><th>操作</th></tr></thead><tbody>@forelse($batch->contentItems as $item)<tr><td><a href="{{ route('admin.reviews.show', $item) }}"><strong>{{ $item->title }}</strong></a></td><td><span class="badge {{ in_array($item->state, ['retryable_failed','needs_manual_review']) ? 'red' : 'teal' }}">{{ $stateLabels[$item->state] ?? $item->state }}</span></td><td>{{ $item->runs->sortByDesc('id')->first()?->created_at?->format('Y-m-d H:i') ?? '-' }}</td><td><a class="button ghost" href="{{ route('admin.reviews.show', $item) }}">查看</a></td></tr>@empty<tr><td colspan="4" class="empty">该批次暂无文章项。</td></tr>@endforelse</tbody></table></div></section>
<section class="panel" style="margin-top:19px"><div class="panel-header"><div><h2>热点标题候选</h2><p>AI 标题只负责表达角度，原始热点来源仍作为文章事实依据。</p></div></div><div class="panel-body"><div class="asset-list">@forelse($titleCandidates as $titleCandidate)<div class="asset"><span class="asset-copy"><strong>{{ $titleCandidate['candidate']->title }}</strong><small>{{ $titleCandidate['item']->topicCandidate?->title ?? '未知选题' }} · {{ $titleCandidate['candidate']->score }} 分 · {{ $titleCandidate['candidate']->rationale ?: '系统生成候选' }}</small></span><form method="post" action="{{ route('admin.batches.title-candidates.select', [$batch, $titleCandidate['candidate']]) }}">@csrf<button class="button ghost" type="submit">{{ $titleCandidate['candidate']->status === 'selected' ? '已选用' : '选用标题' }}</button></form></div>@empty<div class="empty">暂无标题候选。运行任务后，系统会为热点生成候选标题。</div>@endforelse</div></div></section>
@endsection
